server:
  port: 9089
  servlet:
    context-path: /api/v1
spring:
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/carritoCompras?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n"
  level:
      # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: DEBUG